'use server';

import { CreateUserProfileController } from '@/lib/controllers/CreateUserProfileController';

/**
 * BCE Boundary: CreateUserProfileBoundary — CreateUserProfile()
 *
 * Server action for User Story #11: Create User Profile.
 * Sequence: CreateUserProfile(...) → Controller.CreateUserProfile(...) → Entity.CreateUserProfile(...)
 */
export interface CreateUserProfileState {
  success: boolean;
  message: string;
}

export async function createUserProfileAction(
  _prevState: CreateUserProfileState,
  formData: FormData,
): Promise<CreateUserProfileState> {
  const accountId = (formData.get('accountId') as string) ?? '';
  const dob = (formData.get('dob') as string) ?? '';
  const address = (formData.get('address') as string) ?? '';
  const phoneNumber = (formData.get('phoneNumber') as string) ?? '';

  if (!accountId) {
    return { success: false, message: 'Profile already exists' };
  }

  // UserProfile_id is auto-generated by the DB; pass empty string
  const success = await CreateUserProfileController.CreateUserProfile(
    '',
    accountId,
    dob,
    address,
    phoneNumber,
  );

  if (!success) {
    return { success: false, message: 'Profile already exists' };
  }

  return { success: true, message: 'Profile created successfully' };
}
